name: multistage execution

on:
  push:
    branches: [ "new_workflow" ]
  # pull_request:

stages:
  - stage: stage1
    jobs:
      - dep: j1
        runs-on: ubuntu-latest
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
          - uses: actions/checkout@v1
          - script: echo "job 1 run"
      
      - dep2: j2
        runs-on: ubuntu-latest
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
          - uses: actions/checkout@v1
          - script: echo "job 2 run"

  - stage: stage2
    jobs:
      - dep3: j3
        runs-on: ubuntu-latest
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
          - uses: actions/checkout@v1
          - script: echo "job 3 run"
      - dep4: j4
        runs-on: ubuntu-latest
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
          - uses: actions/checkout@v1
          - script: echo "job 4 run"

