name: multistage execution

on:
  push:
    branches: [ "new_workflow" ]
  # pull_request:
    repository_dispatch:
      types: 
        deploy_service

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "job 1 run"
        
    
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v2
      - run: echo "job 2 run"
          
  job3: 
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - uses: actions/checkout@v2
      - run: echo "job 3 run"
          
  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - uses: actions/checkout@v2
      - run: echo "job 4 run"
          

