name: multistage execution

on:
  push:
    branches: [ "new_workflow" ]
  # pull_request:

jobs:
  - job: j1
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - script: echo "job 1 run"
        
    
  - job: j2
    runs-on: ubuntu-latest
    env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - script: echo "job 2 run"
          
  - job: j3
      runs-on: ubuntu-latest
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - uses: actions/checkout@v1
        - script: echo "job 3 run"
          
  - job: j4
      runs-on: ubuntu-latest
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      steps:
        - uses: actions/checkout@v1
        - script: echo "job 4 run"
          

