name: github output file
on: 
  workflow_dispatch
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - updates
        - metadata
      message:
        required: true
jobs:
  greet:
    runs-on: ubuntu-latest
     steps:
     - run: echo "workflow dispatch from user input"   
# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     # Map a step output to a job output
#     outputs:
#       output1: ${{ steps.step1.outputs.test }}
#       output2: ${{ steps.step2.outputs.test }}
#     steps:
#       - id: step1
#         run: echo "::set-output name=test::hello"
#       - id: step2
#         run: echo "::set-output name=test::world"
#   job2:
#     runs-on: ubuntu-latest
#     needs: job1
#     steps:
#       - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
