name: trigger

on:
  push:
    branches: [ "new_workflow" ]
jobs:
 deploy: 
    runs-on: ubuntu-latest
    env:
    SERVICE_NAME: starter-service
    DEPLOYMENT_NOTIFICATION_URL: https://api.github.com/repos/terraform_code2/.github/workflows/dispatches
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
    - name: Notify Deployment Repo
        run: |
          AUTH_HEADER="Authorization: token ${{ steps.get_workflow_token.outputs.token }}"
          PAYLOAD='{ "event_type": "deploy_service", "client_payload": { "service": "'"$SERVICE_NAME"'", "version": "'"$RELEASE_VERSION"'" }}'
          curl --request POST "$DEPLOYMENT_NOTIFICATION_URL" --header "$AUTH_HEADER" --header "Content-Type: application/json" --data-raw "$PAYLOAD" -f -i

##        