name: workflow dispatch user-inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - updates
        - metadata
      message:
        required: true
jobs:
  print-input:
    runs-on: ubuntu-latest
    steps:
      - run: echo "user input workflow"