name: workflow dispatch user-inputs

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      # message:
      ##   required: true
jobs:
  print-input:
    runs-on: ubuntu-latest
    steps:
      - run: echo "user input workflow"