name: terraform execution

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v1  
        name: Download codebase
      
      - name: Bump version and push tag
        uses: actions/checkout@v3

      - uses: anothrNick/github-tag-action@1.40.0
        name: adding tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - uses: actions/checkout@v2
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
      # - uses: rickstaa/action-create-tag@v1
        # with:
        #   tag: "tag-1"
        #   message: "version-1"
      # - uses: actions/checkout@v3
      
      # - name: terraform plan
      #   uses: dflook/terraform-plan@v1
      # - name: configure AWS
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with: 
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1

      # - name: update/create lc asg
      #   run : |
      #     aws autoscaling update-auto-scaling-group --auto-scaling-group-name asg-test20220926080525224900000002 --launch-configuration-name new-lc
      #     aws autoscaling update-auto-scaling-group --auto-scaling-group-name asg-test20220926080525224900000002 --max-size 3
          
